FROM node:18-buster AS build-stage

WORKDIR /app

RUN apt-get update && apt-get install -y openjdk-11-jre-headless

COPY . .

RUN npm install
RUN npm list --depth=0
RUN npx shadow-cljs release prod



FROM nginx:alpine AS production-stage
# Nginx 설정 파일 복사 (필요시 설정)
COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build-stage /app/resources/public /usr/share/nginx/html

# NGINX 실행
CMD ["nginx", "-g", "daemon off;"]
